<?php
/**
 * unit-test:/menu.phtml
 *
 * @creation  2018-04-17
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	...
$dir = ConvertURL('testcase:/');

//	...
$list = App::Session('testcase-menu') ?? $list = ['core'=>[],'unit'=>[]];

//	...
$args = App::Args();
$target = &$list;
while( $arg = array_shift($args) ){
	//	...
	$target = &$target[$arg];
	$join[] = $arg;
	$path = join('/',$join);

	//	...
	if( $handle = opendir($path) ){
		while( false !== ($file = readdir($handle)) ){
			if( $file === '.' or $file === '..' or $file === 'action.php' ){
				continue;
			}

			//	...
			$temp = explode('.', $file);
			$file = $temp[0];

			//	...
			if( $temp[1] and $temp[1] !== 'php' ){
				continue;
			}

			//	...
			$target[$file] = is_dir("$arg/$file") ? []: null;
		}
		closedir($handle);
	}
}

//	...
function _list($list, $dir){
	echo '<ul>';
	foreach( $list as $key => $var ){
		printf('<li><a href="%s">%s</a></li>', $dir.$key, $key);
		if( $var and is_array($var) ){
			_list($var, $dir.$key.'/');
		}
	}
	echo '</ul>';
}
?>
<menu class="testcase">
	<ul>
		<li><a href="<?= $root = ConvertURL('testcase:/') ?>">testcase</a></li>
		<?php _list($list, $root); ?>
	</ul>
</menu>
<style>
menu.testcase {
	border:  1px solid black;
	margin:  0 1em 1em 1em;
	padding: 0.5em 1em;
	float:right;
}
</style>
