<!doctype html>
<html>
	<head>
		<title>The onepiece-framework bootstrap was failed.</title>
	</head>
	<body>
		<header>
			onepiece-framework
		</header>
		<hr/>
		<h1>The onepiece-framework bootstrap was failed.</h1>
		<ol>
			<?php while( $notice = Notice::Get() ): ?>
			<li><?php echo $notice['message'] ?></li>
			<?php endwhile; ?>
		</ol>
		<hr/>
		<footer>
			Copyright 2009 onepiece-framework all right reserved
		</footer>
	</body>
</html>