<?php
/**
 * wordpress2:/app/bootstrap/op/rewrite.php
 *
 * @creation  2016-11-25
 * @version   1.0
 * @package   wordpress2
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	...
global $_OP;

//	Calc rewrite base directory.
$rewrite_base = substr($_OP[APP_ROOT], strlen($_SERVER['DOCUMENT_ROOT']));

?>
<!doctype html>
<html>
<head>
<title>Boot to WordPress2</title>
		<!-- JavaScript -->
		<script type="text/javascript" src="https://onepiece-framework.com/webpack/js/"></script>

		<!-- Stylesheet -->
		<link rel="stylesheet" type="text/css" href="https://onepiece-framework.com/webpack/css/?name=white" />
		<style>
		li {
			margin-bottom: 1em;
		}

		div[role="code"] {
			border: 1px solid #9f9f9f;
			margin:  1em 0;
			padding: 0.7em 1em;
			font-family: monospace;
		}
		</style>
	</head>
	<body>
		<header>
			Boot to WordPress2
		</header>
		<hr/>
		<div data-i18n="true" data-lang="en">
			<h1>How to boot WordPress2.</h1>
			<ol>
				<li>
					<p>Please open <b>"<?= rtrim(ConvertPath('app:/'),'/') ?>/.htaccess"</b> file.</p>
					<p><i><b>Attention!</b> This file is invisible attribute file.</i></p>
				</li>
				<li>
					<p>
						Look for line 38.<br/>
						Change the value of "RewriteEngine" from "Off" to "On".
					</p>
				</li>
				<?php if( $rewrite_base !== '/' ): ?>
				<li>
					<p>
						Look for line 41.<br/>
						Change the value of "RewriteBase" from "/" to "<?= $rewrite_base ?>".
					</p>
				</li>
				<?php endif; ?>
				<li>
					<p>
						Please reload this page.
					</p>
				</li>
			</ol>
		</div>
		<hr/>
		<footer>
			Copyright 2018 all right reserved WordPress2
		</footer>
	</body>
</html>
<?php
exit();